[package]
name = "luck_ecs"
version = "0.1.1"
authors = ["Lucas Bittencourt <lbittencs@gmail.com>"]

[dependencies]
anymap = "0.11.2"
mopa = "0.2.0"
rayon = "0.2.0"

[dev-dependencies]
rand = "*"

[profile.test]
opt-level = 0
debug = true
